apiVersion: apps/v1
kind: Deployment
metadata:
  name: smeagol-galore
  labels:
    run: smeagol-galore
spec:
  replicas: 1
  selector:
    matchLabels:
      run: smeagol-galore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: smeagol-galore
    spec:
      containers:
      - image: schnatterer/smeagol-galore:0.1.1
        imagePullPolicy: IfNotPresent
        name: smeagol-galore
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          #readOnlyRootFilesystem: true
          #privileged: true
          #runAsUser: 0
          #runAsGroup: 0
        volumeMounts:
        - name: users
          mountPath: "/etc/cas/users.txt"
          subPath: "users.txt"
          readOnly: true
        - name: attribs
          mountPath: "/etc/cas/attributes.xml"
          subPath: "attributes.xml"
          readOnly: true
        - name: scm
          mountPath: /home/tomcat/.scm
      volumes:
      - name: users
        secret:
          secretName: smeagol-galore
      - name: attribs
        configMap:
          name: smeagol-galore
      - name: scm
        persistentVolumeClaim:
          claimName: smeagol-galore
      #- name: scm
      #  hostPath:
      #   path: /tmp/data

# TODO Probes: https, /cas/login
# TODO readOnlyRootFilesystem, service account, network policy?
# TODO cert
