apiVersion: apps/v1
kind: Deployment
metadata:
  name: smeagol-galore
  labels:
    run: smeagol-galore
spec:
  replicas: 1
  selector:
    matchLabels:
      run: smeagol-galore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: smeagol-galore
    spec:
      containers:
      - image: schnatterer/smeagol-galore:0.1.1
        imagePullPolicy: IfNotPresent
        name: smeagol-galore
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          #readOnlyRootFilesystem: true
          #privileged: true
          #runAsUser: 0
          #runAsGroup: 0
        volumeMounts:
        # Config
        - name: users
          mountPath: "/etc/cas/users.txt"
          subPath: "users.txt"
          readOnly: true
        - name: attribs
          mountPath: "/etc/cas/attributes.xml"
          subPath: "attributes.xml"
          readOnly: true
        # Persistent data
        - name: scm
          mountPath: /home/tomcat/.scm
      volumes:
      # Config
      - name: users
        secret:
          secretName: smeagol-galore
      - name: attribs
        configMap:
          name: smeagol-galore
      # Persistent data
      - name: scm
        persistentVolumeClaim:
          claimName: smeagol-galore
      #- name: scm
      #  hostPath:
      #    path: /tmp/data
      serviceAccountName: smeagol-galore

# TODO Probes: https, /cas/login. Readiness probe might take > 1 minute (plugin installation)
# TODO cert
# TODO readOnlyRootFilesystem - difficult with auto generated cert  (needs write access to
#    /usr/local/tomcat/conf/keystore.jks and  /etc/ssl/certs/java/cacerts)
